security:
   encoders:
       FOS\UserBundle\Model\UserInterface: sha512

   role_hierarchy:
       ROLE_USER :       ROLE_USER
       ROLE_ADMIN:       ROLE_USER
       ROLE_SUPER_ADMIN: ROLE_ADMIN

   providers:
       fos_userbundle:
           id: fos_user.user_provider.username

   firewalls:
       main:
           pattern: ^/
           anonymous:    true
           form_login:
               check_path: /login_check
               login_path: /login
               success_handler: redirect.after.login
           logout:
               path:    /logout
               target: /
              # provider: fos_userbundle
              # csrf_provider: form.csrf_provider

           

   access_control:
   
       - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/visiteur/, role: ROLE_USER }
       - { path: ^/admin/, role: ROLE_ADMIN }
       