<?php

namespace Ecommerce\EcommerceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AchatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AchatRepository extends EntityRepository
{
	public function getLastId($id){
	  $query = $this->_em->createQuery('SELECT a FROM EcommerceBundle:Achat a WHERE a.id=$id');
	  $results = $query->getResult();
	  return $results;
  }
}