<?php

namespace Ecommerce\EcommerceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{
public function afficherTout()
  {
	  $query = $this->_em->createQuery('SELECT c FROM EcommerceBundle:Categorie c');
	  $results = $query->getResult();
	  return $results;
  }
}
