parameters:
#    user.example.class: Ecommerce\UserBundle\Example

services:
#    user.example:
#        class: %user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    redirect.after.login:
        class: Ecommerce\UserBundle\Redirection\AfterLoginRedirection
        arguments: [@router]
