parameters:
#    visiteur.example.class: Ecommerce\VisiteurBundle\Example

services:
#    visiteur.example:
#        class: %visiteur.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
